language: go

# use containers which run faster and have cache
sudo: false

go:
  - 1.13.x
  - 1.12.x

env:
  - GO111MODULE=on

go_import_path: github.com/metaverse/truss

before_install:
  # protobuf
  # download, unzip in $HOME, add to $PATH
  - wget https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - mv protoc-3.6.1-linux-x86_64.zip $HOME
  - unzip ~/protoc-3.6.1-linux-x86_64.zip -d $HOME
  - export PATH=$HOME/bin/:$PATH

install:
  # install our protoc plugin and truss
  - make dependencies
  - make

script:
  - make test

notifications:
  email: false
