language: go

# use containers which run faster and have cache
sudo: false

go:
  - tip
  - 1.10.x
  - 1.9.x

go_import_path: github.com/tuneinc/truss

before_install:
  # protobuf
  # download, unzip in $HOME, add to $PATH
  - wget https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip
  - mv protoc-3.5.1-linux-x86_64.zip $HOME
  - unzip ~/protoc-3.5.1-linux-x86_64.zip -d $HOME
  - export PATH=$HOME/bin/:$PATH

install:
  # install our protoc plugin and truss
  - make dependencies
  - make

script:
  - make test

notifications:
  email: false
